# Function to read and run a basic cleaning of the data downloaded from sinan tabnet
# arguments:
# fp = file path to data
# rskip = number of rows to skip from the start of the csv file (header comments generated by tabnet)

read_tabnet <- function(fp, rskip){
  year <- readr::read_delim(fp, delim = ";", n_max = rskip, col_names = FALSE,
                         locale = locale(encoding = "latin1")) %>% 
    dplyr::slice(rskip) %>% 
    pull() %>% 
    stringr::str_sub(start = 9) %>% 
    as.double()
  
  df <-readr::read_delim(fp,
                  delim = ";",
                  na = "-",
                  skip = rskip, # remove first rows which contain annotations
                  col_names = TRUE,
                  locale = locale(encoding = "latin1")) %>% 
    suppressWarnings() # there will always be a warning for not properly reading the last rows (annotations) 
  
  if(c("Ign/Em Branco") %in% names(df) == TRUE){
    df <- dplyr::select(df, -"Ign/Em Branco")
  } 
  
  # basic cleaning
  df <- df %>% 
    dplyr::slice(1:(which(`Município de residência` == "Total")-1)) %>% # remove bottom annotations
    dplyr::mutate(across(Jan:Total, ~as.numeric(.)), # make sure all numeric columns are numeric
                  across(everything(), ~ifelse(is.na(.), 0, .)), # replace NAs for zeros
           admin2_id = stringr::str_sub(`Município de residência`, end = 6)) %>% 
    dplyr::filter(!stringr::str_detect(`Município de residência`, "IGNORADO")) %>% # removing rows with "municipio ignorado"
    dplyr::select(-`Município de residência`, -Total) # remove unnecessary columns
  
  # pivot to long format
  df <- df %>% 
    tidyr::pivot_longer(cols = 1:12,
                 names_to = "mon_temp",
                 values_to = "cases") %>% 
    dplyr::mutate(year = year,
           month = case_when(mon_temp == "Jan" ~ 1,
                             mon_temp == "Fev" ~ 2,
                             mon_temp == "Mar" ~ 3,
                             mon_temp == "Abr" ~ 4,
                             mon_temp == "Mai" ~ 5,
                             mon_temp == "Jun" ~ 6,
                             mon_temp == "Jul" ~ 7,
                             mon_temp == "Ago" ~ 8,
                             mon_temp == "Set" ~ 9,
                             mon_temp == "Out" ~ 10,
                             mon_temp == "Nov" ~ 11,
                             mon_temp == "Dez" ~ 12)) %>% 
    dplyr::select(-mon_temp)
  
  return(df)
  
}

